### ISSUE TITLE
`:help numbertoggle` doesn't seem to work

### ISSUE THREAD

**Issue by meowsus** [jeffkreeftmeijer/vim-numbertoggle#31]
Installed with pathogen. The `:help numbertoggle` command doesn't work, and I wasn't able to find anything other comparable command to run.

**Comment by klaernie** [comment]
@meowsus : you need to run `:Helptags` like specified in the [pathogen readme](https://github.com/tpope/vim-pathogen#runtime-path-manipulation). Or as @tpope says: [get crazy](https://github.com/klaernie/vimrc/blob/238833de67165b03abb1a593ccb82d70b5b7d96f/.vimrc#L41)
