### ISSUE TITLE
Generally questionable use of autocommands

### ISSUE THREAD

**Issue by unphased** [jeffkreeftmeijer/vim-numbertoggle#34]
I ran into this issue today and tracked it down to this plugin. 

http://vi.stackexchange.com/questions/7164/some-local-to-window-settings-are-being-reset-in-vim

Since I don't use the plugin (or relativenumbers) ever, I easily fixed the issue by removing this plugin. 

But I am also positive that the behavior and function of the plugin can be kept while not being nearly so overzealous with the autocommands.

Anyway, just a heads-up.

**Comment by jeffkreeftmeijer** [comment]
Hey @unphased, sorry for taking so long to get to this. Thanks for letting me know! Fixed in db234b2417c3780306d201be1369ff06498f6697.
