### ISSUE TITLE
Keeps previous window in relative mode when opening new split window

### ISSUE THREAD

**Issue by fernandoacorreia** [jeffkreeftmeijer/vim-numbertoggle#39]
Steps to reproduce
* Open a file.
* Type `:Vexplore`.
* Open another file from the list.
* Notice that there are now two buffers, in two split windows, and both are in relative mode.
* Switch between windows (`Ctrl+W w`).
* Notice that now only one window is in relative mode at a time (as it should be).

![screenshot from 2017-09-28 21-05-47](https://user-images.githubusercontent.com/17158/31000515-ed74da18-a490-11e7-9628-4fafcec216d1.png)

**Comment by jeffkreeftmeijer** [comment]
Hey @fernandoacorreia 👋

Thanks for reporting this, I'm able to reproduce this locally. This seems to happen when opening a new split too.

1. Open a file
2. `:split`
3. Both buffers have relative line numbers

**Comment by fernandoacorreia** [comment]
> this seems to happen when opening a new split too

Indeed. I thought that could be by design, because it's the same buffer. But ideally only one window would have relative numbers at a time.

**Comment by jeffkreeftmeijer** [comment]
I'd be fine with it if it just happened when you have the same buffer open in two splits, but would like this to work when you open another file in a new split (like in [Fernando's example](https://github.com/jeffkreeftmeijer/vim-numbertoggle/issues/39#issue-261526692) and in [mine](https://github.com/jeffkreeftmeijer/vim-numbertoggle/issues/39#issuecomment-333064614)). I haven't found a way to do that yet, so I'm open for suggestions or a pull request.

**Comment by brendanator** [comment]
Adding `WinEnter`/`WinLeave` hooks works for me

**Comment by jeffkreeftmeijer** [comment]
Adding `WinEnter` and `WinLeave` hooks worked for me too. cfaecb9 adds them and should close this issue. Thanks @brendanator! @fernandoacorreia could you try the current master?

**Comment by fernandoacorreia** [comment]
`master` works for me. As soon as you type `:Vexplore` the original window switches to absolute line numbers; the new window is in relative mode; switching between windows works as expected (only one in relative mode at a time).

Great job @brendanator ! And thanks, @jeffkreeftmeijer .
