### ISSUE TITLE
What is the name of font&colorscheme on the screenshot in README?

### ISSUE THREAD

**Issue by semanser** [jeffkreeftmeijer/vim-numbertoggle#43]
Sorry for the offtopic :)

**Comment by jeffkreeftmeijer** [comment]
No problem at all, and sorry for missing this message until now. If you're still looking, that's Apple's SF Mono, https://github.com/jeffkreeftmeijer/vim-dim and https://github.com/jeffkreeftmeijer/appsignal.terminal.
