### ISSUE TITLE
Automatic line number toggle does not work inside tmux

### ISSUE THREAD

**Issue by jdhao** [jeffkreeftmeijer/vim-numbertoggle#45]
I read your post [here](https://jeffkreeftmeijer.com/vim-number/) and the automatic number toggle works great. The settings I use:

```
augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END
```

But it seems that this setting does not work inside tmux.  If I open two tmux panes side by side and open  a file with Neovim in one pane and then switch to another tmux pane, the relative line number in Neovim does not change to absolute number. How to fix this issue?

Besides, I use `set -g mouse on` inside `~/.tmux.conf` so that I can use mouse to change tmux panes, if that information is relevant.

**Comment by jdhao** [comment]
I have installed this plugin. It does not work.

**Comment by jeffkreeftmeijer** [comment]
I’m afraid I can’t reproduce this myself. I have `set -g mouse on` in my `.tmux.conf`, and toggling seems to work both when switching with the keyboard, and clicking the other pane with the mouse.

Could you make sure you have the most recent version of vim-numbertoggle installed, and have removed the code snippet from the article from your Vim configuration files?

**Comment by jdhao** [comment]
Yes, I am using the latest version of vim-numbertoggle and have removed the the simpler code snippet.
![video_2019-01-11_143945](https://user-images.githubusercontent.com/16662357/51017445-10fd3300-15af-11e9-85ed-962b72366162.gif)

**Comment by jdhao** [comment]
I have filed [an issue](https://github.com/neovim/neovim/issues/9486) on Neovim repo and got the right answer. 

We need to turn on the `focus-events` for tmux. Edit the tmux config file `~/.tmux.conf` and add the following setting:

```
set -g focus-events on
```

**Comment by NilsIrl** [comment]
I think this should be mentioned in the README

**Comment by MahdiNazemi** [comment]
Does adding `set-option -g focus-events on` still work? I have a Mac and a Linux machine, but I couldn't get the plugin to work correctly on either machine.

Running tmux 3.3a and Vim 9.0 on one machine and tmux 3.0a and Vim 8.1 on the other.

**Comment by 2knarf** [comment]
Looks like this issue is back, the mentioned fix does not work.

tmux 3.3a
nvim 0.9.5

**Comment by MahdiNazemi** [comment]
What worked for me was to install the `'tmux-plugins/vim-tmux-focus-events'`Vim [plugin](https://github.com/tmux-plugins/vim-tmux-focus-events).

Although the plugin's README mentions that newer versions of Vim have native support for reporting focus events and, therefore, one should not need to install the plugin, installing it helped resolve the issue on all my machines.
