### ISSUE TITLE
Option to toggle to absolute numbers in command mode

### ISSUE THREAD

**Issue by tversteeg** [jeffkreeftmeijer/vim-numbertoggle#48]
I would like to be able to set the numbers to absolute when I press `:`. Is this something that could be added to this plugin? I can understand it if other people don't want this option, so maybe it should be configurable?

**Comment by seymar** [comment]
There is no autocmd event for that:

http://vimdoc.sourceforge.net/htmldoc/autocmd.html#autocmd-events

**Comment by jeffkreeftmeijer** [comment]
Since number toggle only toggles relative numbers, you could toggle using the `F2` key by remapping it:

    :nnoremap <F2> :set nornur!<CR>

**Comment by mmirus** [comment]
FYI, I think the `CmdlineEnter` and `CmdlineLeave` events can be used for this now.

**Comment by simonmandlik** [comment]
I achieved this with the following:

```
augroup numbertoggle
autocmd!
autocmd BufEnter,FocusGained,InsertLeave,CmdlineLeave,WinEnter * if &number && mode() != "i" | set relativenumber | redraw | endif
autocmd BufLeave,FocusLost,InsertEnter,CmdlineEnter,WinLeave   * if &number | set norelativenumber | redraw | endif
augroup END
```
