### ISSUE TITLE
How did you made the "space" behind line number disappear in the screenshots?

### ISSUE THREAD

**Issue by BSDxxxx** [jeffkreeftmeijer/vim-numbertoggle#49]
![image](https://user-images.githubusercontent.com/59258592/82233986-5c71df00-9963-11ea-8bfe-c604d484bb82.png)
![image](https://user-images.githubusercontent.com/59258592/82233978-58de5800-9963-11ea-838a-58963f43c4db.png)

**Comment by chr1sto14** [comment]
Looks like the width of the line number corresponds to the number of lines in the file. Open a file with 1000 lines vs a file with 100 lines to compare.

**Comment by jeffkreeftmeijer** [comment]
That screenshot shouldn’t have any special configuration set up to make that happen, I think not having an extra space there is the default. However, if you’d like you can set the width of the number bar using `:set numberwidth`.
